In [1]:
# Read data from csv
import matplotlib.pyplot as plt
import numpy as np
import csv

# Load data from CSV file using numpy

Data = np.loadtxt(r"C:\Users\hp\Documents\Linear DA.csv",delimiter = ',' , skiprows = 1)
print(Data)

[[0.         0.05978099 0.49191777]
 [0.         0.06600874 0.51372384]
 [0.         0.0773155  0.47890498]
 [0.         0.15122809 0.7272318 ]
 [0.         0.13512039 0.78356806]
 [0.         0.13278641 0.738307  ]
 [0.         0.15076233 0.76263767]
 [0.         0.16051433 0.71985791]
 [0.         0.14223942 0.77099205]
 [0.         0.13432878 0.80450525]
 [0.         0.15702051 0.73369288]
 [0.         0.13855052 0.75204201]
 [0.         0.13734274 0.73614996]
 [0.         0.18122546 0.53708   ]
 [0.         0.18311528 0.5713942 ]
 [0.         0.17427211 0.63519918]
 [0.         0.1908463  0.53880958]
 [0.         0.17124697 0.58641951]
 [0.         0.16834595 0.55974232]
 [0.         0.17363138 0.51826856]
 [0.         0.17275429 0.52308112]
 [0.         0.18101539 0.47531747]
 [0.         0.16353585 0.5424224 ]
 [0.         0.1702128  0.48796572]
 [0.         0.16042248 0.56742361]
 [0.         0.16469984 0.60402049]
 [0.         0.1695788  0.54370854]
 [0.         0.169021   0.47

In [2]:
# Extract X1 , X2 and Class
C = Data[:len(Data),0:1]
print(" Class is ")
print(" ")
print(C)

print(" ")
print(" X1 is ")
print(" ")
X1 = Data[:len(Data),1:2]
print(X1)

print(" ")
print(" X2 is ")
print(" ")
X2 = Data[:len(Data),2:3]
print(X2)

 Class is 
 
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
 
 X1 is 
 
[[0.05978099]
 [0.06600874]
 [0.0773155 ]
 [0.15122809]
 [0.13512039]
 [0.13278641]
 [0.15076233]
 [0.16051433]
 [0.14223942]
 [0.13432878]
 [0.15702051]
 [0.13855052]
 [0.13734274]
 [0.18122546]
 [0.18311528]
 [0.17427211]
 [0.1908463 ]
 [0.17124697]
 [0.16834595]
 [0.17363138]
 [0.17275429]
 [0.18101539]
 [0.16353585]
 [0.1702128 ]
 [0.16042248]
 [0.16469984]
 [0.1695788 ]
 [0.169021  ]
 [0.16734024]
 [0.18052782]
 [0.15810799]
 [0.18285544]
 [0.19980652]
 [0.19528037]
 [0.20850437]
 [0.16842574]
 [0.17998186]
 [0.20451797]
 [0.1982922 ]
 [0.18424982]
 [0.19179436]
 [0.19300411]
 [0.1908901 ]
 [0.18

In [3]:
# Normalization of X1 
m_x1 = np.mean(X1)
SD1 = np.std(X1)
norm_x1 = []
for xi in X1:
    norm_x1.append((xi-m_x1)/SD1)
print("Normalization of x1 is ")
print(" ")
print(np.array(norm_x1))

Normalization of x1 is 
 
[[-3.00536516e+00]
 [-2.81517194e+00]
 [-2.46986780e+00]
 [-2.12606061e-01]
 [-7.04529110e-01]
 [-7.75807952e-01]
 [-2.26830251e-01]
 [ 7.09920990e-02]
 [-4.87116701e-01]
 [-7.28704572e-01]
 [-3.57078362e-02]
 [-5.99774151e-01]
 [-6.36659252e-01]
 [ 7.03501867e-01]
 [ 7.61216296e-01]
 [ 4.91149139e-01]
 [ 9.97318550e-01]
 [ 3.98762722e-01]
 [ 3.10166546e-01]
 [ 4.71581524e-01]
 [ 4.44795567e-01]
 [ 6.97086563e-01]
 [ 1.63268176e-01]
 [ 3.67179481e-01]
 [ 6.81868830e-02]
 [ 1.98815825e-01]
 [ 3.47817459e-01]
 [ 3.30782555e-01]
 [ 2.79452645e-01]
 [ 6.82196273e-01]
 [-2.49668081e-03]
 [ 7.53280883e-01]
 [ 1.27096022e+00]
 [ 1.13273329e+00]
 [ 1.53658911e+00]
 [ 3.12603455e-01]
 [ 6.65522776e-01]
 [ 1.41484616e+00]
 [ 1.22471347e+00]
 [ 7.95864737e-01]
 [ 1.02627212e+00]
 [ 1.06321735e+00]
 [ 9.98656093e-01]
 [ 8.03027803e-01]
 [ 9.25820281e-01]
 [ 1.19979306e+00]
 [ 8.22767297e-02]
 [-2.98535060e-01]
 [-1.49274948e+00]
 [-3.56651909e-01]
 [-1.44948521e+00]
 [-4.

In [4]:
# Normaliztion of X2 is
m_x2 = np.mean(X2)
SD2 = np.std(X2)
norm_x2 = []
for xi in X2:
    norm_x2.append((xi-m_x2)/SD2)
print("Normalization of x2 is ")
print(" ")
print(np.array(norm_x2))

Normalization of x2 is 
 
[[-0.56485823]
 [-0.41664746]
 [-0.65330308]
 [ 1.03451583]
 [ 1.41742012]
 [ 1.10979139]
 [ 1.2751612 ]
 [ 0.98439723]
 [ 1.33194398]
 [ 1.5597253 ]
 [ 1.07843027]
 [ 1.20314501]
 [ 1.09513044]
 [-0.2579012 ]
 [-0.02467561]
 [ 0.40899178]
 [-0.24614559]
 [ 0.07744789]
 [-0.10387072]
 [-0.38575811]
 [-0.35304823]
 [-0.67768653]
 [-0.2215901 ]
 [-0.59171938]
 [-0.05166276]
 [ 0.19707755]
 [-0.21284851]
 [-0.66118227]
 [-0.24159511]
 [-1.77802167]
 [ 0.70821346]
 [-0.46847256]
 [-1.01771709]
 [-0.34538374]
 [-1.57329038]
 [-0.56627453]
 [ 0.03568068]
 [-1.12446533]
 [-0.84994641]
 [-0.32677904]
 [-2.13713877]
 [-2.02200342]
 [-1.80481882]
 [-1.61288809]
 [-1.72190522]
 [-2.073397  ]
 [-0.04072739]
 [ 1.01003832]
 [ 0.31943154]
 [ 1.17023894]
 [ 1.17141548]
 [ 0.82840399]
 [ 1.01636635]
 [ 1.27394353]
 [ 0.30888681]
 [ 1.31702109]
 [ 0.59566868]
 [ 0.97463805]
 [ 0.17849013]
 [ 0.77336097]
 [ 0.67274633]]


In [5]:
# Now making X matrix
X = np.hstack((np.array(norm_x1) , np.array(norm_x2)))
print(X)

[[-3.00536516e+00 -5.64858230e-01]
 [-2.81517194e+00 -4.16647460e-01]
 [-2.46986780e+00 -6.53303079e-01]
 [-2.12606061e-01  1.03451583e+00]
 [-7.04529110e-01  1.41742012e+00]
 [-7.75807952e-01  1.10979139e+00]
 [-2.26830251e-01  1.27516120e+00]
 [ 7.09920990e-02  9.84397226e-01]
 [-4.87116701e-01  1.33194398e+00]
 [-7.28704572e-01  1.55972530e+00]
 [-3.57078362e-02  1.07843027e+00]
 [-5.99774151e-01  1.20314501e+00]
 [-6.36659252e-01  1.09513044e+00]
 [ 7.03501867e-01 -2.57901196e-01]
 [ 7.61216296e-01 -2.46756123e-02]
 [ 4.91149139e-01  4.08991783e-01]
 [ 9.97318550e-01 -2.46145587e-01]
 [ 3.98762722e-01  7.74478948e-02]
 [ 3.10166546e-01 -1.03870724e-01]
 [ 4.71581524e-01 -3.85758110e-01]
 [ 4.44795567e-01 -3.53048232e-01]
 [ 6.97086563e-01 -6.77686526e-01]
 [ 1.63268176e-01 -2.21590100e-01]
 [ 3.67179481e-01 -5.91719383e-01]
 [ 6.81868830e-02 -5.16627638e-02]
 [ 1.98815825e-01  1.97077549e-01]
 [ 3.47817459e-01 -2.12848509e-01]
 [ 3.30782555e-01 -6.61182269e-01]
 [ 2.79452645e-01 -2

In [6]:
# Extract data for class 0
C0 = X[:31,0:2]
print(" Data for class 0")
print(" ")
print(C0)

 Data for class 0
 
[[-3.00536516e+00 -5.64858230e-01]
 [-2.81517194e+00 -4.16647460e-01]
 [-2.46986780e+00 -6.53303079e-01]
 [-2.12606061e-01  1.03451583e+00]
 [-7.04529110e-01  1.41742012e+00]
 [-7.75807952e-01  1.10979139e+00]
 [-2.26830251e-01  1.27516120e+00]
 [ 7.09920990e-02  9.84397226e-01]
 [-4.87116701e-01  1.33194398e+00]
 [-7.28704572e-01  1.55972530e+00]
 [-3.57078362e-02  1.07843027e+00]
 [-5.99774151e-01  1.20314501e+00]
 [-6.36659252e-01  1.09513044e+00]
 [ 7.03501867e-01 -2.57901196e-01]
 [ 7.61216296e-01 -2.46756123e-02]
 [ 4.91149139e-01  4.08991783e-01]
 [ 9.97318550e-01 -2.46145587e-01]
 [ 3.98762722e-01  7.74478948e-02]
 [ 3.10166546e-01 -1.03870724e-01]
 [ 4.71581524e-01 -3.85758110e-01]
 [ 4.44795567e-01 -3.53048232e-01]
 [ 6.97086563e-01 -6.77686526e-01]
 [ 1.63268176e-01 -2.21590100e-01]
 [ 3.67179481e-01 -5.91719383e-01]
 [ 6.81868830e-02 -5.16627638e-02]
 [ 1.98815825e-01  1.97077549e-01]
 [ 3.47817459e-01 -2.12848509e-01]
 [ 3.30782555e-01 -6.61182269e-01]


In [7]:
# Extract data for class 1
C1 = X[31:,0:2]
print(" Data for class 1")
print(" ")
print(C1)

 Data for class 1
 
[[ 0.75328088 -0.46847256]
 [ 1.27096022 -1.01771709]
 [ 1.13273329 -0.34538374]
 [ 1.53658911 -1.57329038]
 [ 0.31260345 -0.56627453]
 [ 0.66552278  0.03568068]
 [ 1.41484616 -1.12446533]
 [ 1.22471347 -0.84994641]
 [ 0.79586474 -0.32677904]
 [ 1.02627212 -2.13713877]
 [ 1.06321735 -2.02200342]
 [ 0.99865609 -1.80481882]
 [ 0.8030278  -1.61288809]
 [ 0.92582028 -1.72190522]
 [ 1.19979306 -2.073397  ]
 [ 0.08227673 -0.04072739]
 [-0.29853506  1.01003832]
 [-1.49274948  0.31943154]
 [-0.35665191  1.17023894]
 [-1.44948521  1.17141548]
 [-0.04996333  0.82840399]
 [ 0.07803252  1.01636635]
 [-1.2210717   1.27394353]
 [-1.08365927  0.30888681]
 [ 0.16834224  1.31702109]
 [-1.36057927  0.59566868]
 [-0.28057737  0.97463805]
 [ 0.18127445  0.17849013]
 [-1.43222297  0.77336097]
 [-1.69196389  0.67274633]]


In [10]:
# Now finding mean for class 0
M0 = np.mean(C0)
print("Mean of data  for class 0 is")
print(" ")
print(M0)

Mean of data  for class 0 is
 
0.01810499348210872


In [11]:
# Now finding mean for class 1
M1 = np.mean(C1)
print("Mean of data  for class 1 is")
print(" ")
print(M1)

Mean of data  for class 1 is
 
-0.018708493264845805


In [20]:
# Now finding  terms for scatter matrix SW
c0 = np.array(C0)
first = []
for i in range(len(c0)):
    first.append(c0[i] - M0)

First = np.array(first)
    
print(First)

[[-3.02347015 -0.58296322]
 [-2.83327694 -0.43475245]
 [-2.48797279 -0.67140807]
 [-0.23071105  1.01641084]
 [-0.7226341   1.39931512]
 [-0.79391295  1.0916864 ]
 [-0.24493524  1.25705621]
 [ 0.05288711  0.96629223]
 [-0.50522169  1.31383899]
 [-0.74680957  1.54162031]
 [-0.05381283  1.06032527]
 [-0.61787914  1.18504002]
 [-0.65476425  1.07702545]
 [ 0.68539687 -0.27600619]
 [ 0.7431113  -0.04278061]
 [ 0.47304415  0.39088679]
 [ 0.97921356 -0.26425058]
 [ 0.38065773  0.0593429 ]
 [ 0.29206155 -0.12197572]
 [ 0.45347653 -0.4038631 ]
 [ 0.42669057 -0.37115323]
 [ 0.67898157 -0.69579152]
 [ 0.14516318 -0.23969509]
 [ 0.34907449 -0.60982438]
 [ 0.05008189 -0.06976776]
 [ 0.18071083  0.17897256]
 [ 0.32971247 -0.2309535 ]
 [ 0.31267756 -0.67928726]
 [ 0.26134765 -0.25970011]
 [ 0.66409128 -1.79612666]
 [-0.02060167  0.69010847]]


In [21]:
# taking transpose
First_trans = First.T
print(First_trans)

[[-3.02347015 -2.83327694 -2.48797279 -0.23071105 -0.7226341  -0.79391295
  -0.24493524  0.05288711 -0.50522169 -0.74680957 -0.05381283 -0.61787914
  -0.65476425  0.68539687  0.7431113   0.47304415  0.97921356  0.38065773
   0.29206155  0.45347653  0.42669057  0.67898157  0.14516318  0.34907449
   0.05008189  0.18071083  0.32971247  0.31267756  0.26134765  0.66409128
  -0.02060167]
 [-0.58296322 -0.43475245 -0.67140807  1.01641084  1.39931512  1.0916864
   1.25705621  0.96629223  1.31383899  1.54162031  1.06032527  1.18504002
   1.07702545 -0.27600619 -0.04278061  0.39088679 -0.26425058  0.0593429
  -0.12197572 -0.4038631  -0.37115323 -0.69579152 -0.23969509 -0.60982438
  -0.06976776  0.17897256 -0.2309535  -0.67928726 -0.25970011 -1.79612666
   0.69010847]]


In [23]:
# Now finding first term
first_term = First_trans.dot(First)
print(first_term)

[[30.43156152 -3.91797982]
 [-3.91797982 21.32265783]]


In [26]:
c1 = np.array(C1)
second = []
for i in range(len(c1)):
    second.append(c1[i] - M1)

Second = np.array(second)
    
print(Second)

[[ 0.77198938 -0.44976407]
 [ 1.28966871 -0.9990086 ]
 [ 1.15144179 -0.32667524]
 [ 1.55529761 -1.55458189]
 [ 0.33131195 -0.54756603]
 [ 0.68423127  0.05438918]
 [ 1.43355465 -1.10575684]
 [ 1.24342197 -0.83123792]
 [ 0.81457323 -0.30807054]
 [ 1.04498061 -2.11843028]
 [ 1.08192584 -2.00329492]
 [ 1.01736459 -1.78611033]
 [ 0.8217363  -1.5941796 ]
 [ 0.94452877 -1.70319673]
 [ 1.21850155 -2.0546885 ]
 [ 0.10098522 -0.02201889]
 [-0.27982657  1.02874681]
 [-1.47404099  0.33814003]
 [-0.33794342  1.18894743]
 [-1.43077671  1.19012398]
 [-0.03125484  0.84711248]
 [ 0.09674101  1.03507484]
 [-1.2023632   1.29265202]
 [-1.06495077  0.32759531]
 [ 0.18705073  1.33572959]
 [-1.34187078  0.61437717]
 [-0.26186888  0.99334654]
 [ 0.19998295  0.19719863]
 [-1.41351447  0.79206946]
 [-1.67325539  0.69145482]]


In [27]:
# taking transpose
Second_trans = Second.T
print(Second_trans)

[[ 0.77198938  1.28966871  1.15144179  1.55529761  0.33131195  0.68423127
   1.43355465  1.24342197  0.81457323  1.04498061  1.08192584  1.01736459
   0.8217363   0.94452877  1.21850155  0.10098522 -0.27982657 -1.47404099
  -0.33794342 -1.43077671 -0.03125484  0.09674101 -1.2023632  -1.06495077
   0.18705073 -1.34187078 -0.26186888  0.19998295 -1.41351447 -1.67325539]
 [-0.44976407 -0.9990086  -0.32667524 -1.55458189 -0.54756603  0.05438918
  -1.10575684 -0.83123792 -0.30807054 -2.11843028 -2.00329492 -1.78611033
  -1.5941796  -1.70319673 -2.0546885  -0.02201889  1.02874681  0.33814003
   1.18894743  1.19012398  0.84711248  1.03507484  1.29265202  0.32759531
   1.33572959  0.61437717  0.99334654  0.19719863  0.79206946  0.69145482]]


In [28]:
# Now finding second term
second_term = Second_trans.dot(Second)
print(second_term)

[[ 30.95107747 -26.85850755]
 [-26.85850755  39.25337969]]


In [31]:
#Now finding scatter matrix SW
print("Scatter matrix is ")
print(" ")
SW = first_term + second_term
print(SW)

Scatter matrix is 
 
[[ 61.38263899 -30.77648737]
 [-30.77648737  60.57603752]]


In [32]:
# Now finding inverse of scatter matrix SW
SW_inver = np.linalg.inv(SW)
print(" Inverse of scatter matrix is  ")
print(" ")
print(SW_inver)

 Inverse of scatter matrix is  
 
[[0.02185973 0.01110614]
 [0.01110614 0.0221508 ]]


In [34]:
# Now finding best direction that is W 
W = SW_inver*(M1-M0)
print(" Best direction W is ")
print(" ")
print(W)

 Best direction W is 
 
[[-0.00080473 -0.00040886]
 [-0.00040886 -0.00081545]]
